[project]
name = "provider-simenv"
version = "0.1.0"
description = "A Simulation Environment for Supply Chain Security"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "Melodie>=0.6.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.4",
    "tox-uv>=1.33.0",
    "tox>=4.47.0",
]

[tool.ruff]
line-length = 78

[tool.setuptools.packages.find]
where = ["src"]
