[tox]
envlist = lint, typecheck, test
requires =
    tox-uv

[testenv]
description = Run unit tests
runner = uv-venv-runner
deps =
    pytest
commands =
    pytest tests

[testenv:lint]
description = Lint with ruff
runner = uv-venv-runner
deps =
    ruff
commands =
    ruff check .

[testenv:typecheck]
description = Type check with ty
runner = uv-venv-runner
deps =
    ty
commands =
    ty check .
