import baseTemplate from './templates/s1-soja.template.pdl.yaml?raw'
import rosterTemplate from './templates/s1-soja.template.roster.yaml?raw'

export type CascadeId = 'soy_crisis_cascade' | 'energy_food_cascade'

interface SoyConfig {
  droughtLossPct: number
  droughtDurationDays: number
  droughtDay: number
  portCongestionEnabled: boolean
  portCongestionLossPct: number
  portCongestionDurationDays: number
  portCongestionDay: number
  argentinaSupplyEnabled: boolean
  argentinaSupplyDay: number
  usEmergencyEnabled: boolean
  usEmergencyDay: number
  reserveReleaseEnabled: boolean
  reserveReleaseDay: number
  alternativeProteinEnabled: boolean
  alternativeProteinDay: number
}

interface EnergyConfig {
  gasPriceIncreasePct: number
  gasPriceDurationDays: number
  gasPriceDay: number
  ammoniaHaltEnabled: boolean
  ammoniaHaltLossPct: number
  ammoniaHaltDurationDays: number
  ammoniaHaltDay: number
  oilMillSlowdownEnabled: boolean
  oilMillSlowdownLossPct: number
  oilMillSlowdownDurationDays: number
  oilMillSlowdownDay: number
  reserveReleaseEnabled: boolean
  reserveReleaseDay: number
  alternativeProteinEnabled: boolean
  alternativeProteinDay: number
}

export interface ScenarioConfig {
  scenarioName: string
  cascadeId: CascadeId
  soy: SoyConfig
  energy: EnergyConfig
}

export const defaultScenarioConfig: ScenarioConfig = {
  scenarioName: 'Interactive supply chain scenario',
  cascadeId: 'soy_crisis_cascade',
  soy: {
    droughtLossPct: 40,
    droughtDurationDays: 90,
    droughtDay: 0,
    portCongestionEnabled: true,
    portCongestionLossPct: 20,
    portCongestionDurationDays: 30,
    portCongestionDay: 21,
    argentinaSupplyEnabled: true,
    argentinaSupplyDay: 14,
    usEmergencyEnabled: true,
    usEmergencyDay: 45,
    reserveReleaseEnabled: true,
    reserveReleaseDay: 28,
    alternativeProteinEnabled: true,
    alternativeProteinDay: 35,
  },
  energy: {
    gasPriceIncreasePct: 200,
    gasPriceDurationDays: 180,
    gasPriceDay: 0,
    ammoniaHaltEnabled: true,
    ammoniaHaltLossPct: 70,
    ammoniaHaltDurationDays: 90,
    ammoniaHaltDay: 7,
    oilMillSlowdownEnabled: true,
    oilMillSlowdownLossPct: 30,
    oilMillSlowdownDurationDays: 60,
    oilMillSlowdownDay: 14,
    reserveReleaseEnabled: true,
    reserveReleaseDay: 21,
    alternativeProteinEnabled: true,
    alternativeProteinDay: 28,
  },
}

function normalizeTemplate(rawTemplate: string): string {
  return rawTemplate.replace(/\r\n/g, '\n').trimEnd() + '\n'
}

const normalizedBaseTemplate = normalizeTemplate(baseTemplate)
const normalizedRosterTemplate = normalizeTemplate(rosterTemplate)

const GENERATED_HEADER = [
  '# Generated by the integrated simenv scenario configurator.',
  '# Save this document as *.pdl.yaml and pass it to provider_simenv.main with --pdl.',
  '',
].join('\n')

const GENERATED_ROSTER_HEADER = [
  '# Generated by the integrated simenv scenario configurator.',
  '# Keep this sidecar beside the generated *.pdl.yaml file so simenv can load the added topology.',
  '',
].join('\n')

const CASCADE_LABEL: Record<CascadeId, string> = {
  soy_crisis_cascade: 'Soy crisis cascade',
  energy_food_cascade: 'Energy-food cascade',
}

const SOY_TIMELINE_OFFSETS = {
  brazil_drought: 0,
  soy_export_reduction: 14,
  argentina_supply_increase: 14,
  port_congestion: 21,
  port_route_shift: 21,
  feed_price_spike: 28,
  reserve_release: 28,
  alternative_protein_activation: 35,
  livestock_pressure: 42,
  us_supply_activated: 45,
  consumer_price_increase: 60,
  consumer_substitution: 75,
  feed_demand_reduction: 90,
} as const

const ENERGY_TIMELINE_OFFSETS = {
  gas_price_spike: 0,
  ammonia_halt: 7,
  oil_mill_slowdown: 14,
  soy_oil_shortage: 18,
  feed_price_spike: 21,
  reserve_release: 21,
  alternative_protein_activation: 28,
  livestock_pressure: 35,
  consumer_price_increase: 50,
  consumer_substitution: 65,
} as const

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function replaceScenarioName(doc: string, name: string): string {
  const scenarioName = name.trim() || defaultScenarioConfig.scenarioName
  return doc.replace(/(^scenario:\n(?: {2}.*\n)+? {2}name: ).*$/m, `$1${JSON.stringify(scenarioName)}`)
}

function eventBlockPattern(eventId: string): RegExp {
  return new RegExp(`(^  - id: ${escapeRegex(eventId)}\\n[\\s\\S]*?)(?=^  - id: |^cascades:|(?![\\s\\S]))`, 'm')
}

function cascadeBlockPattern(cascadeId: CascadeId): RegExp {
  return new RegExp(`(^  - id: ${escapeRegex(cascadeId)}\\n[\\s\\S]*?)(?=^  - id: |(?![\\s\\S]))`, 'm')
}

function timelineEntryPattern(eventId: string): RegExp {
  return new RegExp(
    `(^      - at: .*\\n        event: ${escapeRegex(eventId)}\\n[\\s\\S]*?)(?=^      - at: |^    probability:|(?![\\s\\S]))`,
    'm',
  )
}

function updateEventBlock(
  doc: string,
  eventId: string,
  updater: (block: string) => string,
): string {
  const pattern = eventBlockPattern(eventId)
  const match = doc.match(pattern)
  if (!match) throw new Error(`Missing event block: ${eventId}`)
  return doc.replace(pattern, updater(match[0]))
}

function updateCascadeBlock(
  doc: string,
  cascadeId: CascadeId,
  updater: (block: string) => string,
): string {
  const pattern = cascadeBlockPattern(cascadeId)
  const match = doc.match(pattern)
  if (!match) throw new Error(`Missing cascade block: ${cascadeId}`)
  return doc.replace(pattern, updater(match[0]))
}

function replaceImpact(block: string, field: 'supply' | 'price', value: string): string {
  return block.replace(new RegExp(`(^      ${field}: ).*$`, 'm'), `$1${JSON.stringify(value)}`)
}

function replaceDuration(block: string, durationDays: number): string {
  return block.replace(/^ {6}duration: .*$/m, `      duration: ${Math.round(durationDays)}d`)
}

function replaceCondition(block: string, condition: string | null): string {
  if (condition === null) return block.replace(/^ {6}condition: .*$\n/m, '')
  if (/^ {6}condition: /m.test(block)) {
    return block.replace(/^ {6}condition: .*$/m, `      condition: ${JSON.stringify(condition)}`)
  }
  return block
}

function setTimelineDay(block: string, eventId: string, day: number): string {
  const pattern = timelineEntryPattern(eventId)
  const match = block.match(pattern)
  if (!match) throw new Error(`Missing timeline entry: ${eventId}`)
  return block.replace(pattern, match[0].replace(/^ {6}- at: .*$/m, `      - at: ${Math.round(day)}d`))
}

function setTimelineEnabled(block: string, eventId: string, enabled: boolean, day: number): string {
  const pattern = timelineEntryPattern(eventId)
  const match = block.match(pattern)
  if (!match) throw new Error(`Missing timeline entry: ${eventId}`)
  if (!enabled) return block.replace(pattern, '')
  return block.replace(pattern, match[0].replace(/^ {6}- at: .*$/m, `      - at: ${Math.round(day)}d`))
}

function setTimelineDays(block: string, days: Record<string, number>): string {
  let next = block
  for (const [eventId, day] of Object.entries(days)) {
    next = setTimelineDay(next, eventId, day)
  }
  return next
}

function keepOnlyCascade(doc: string, cascadeBlock: string): string {
  return doc.replace(/^cascades:\n[\s\S]*$/m, `cascades:\n${cascadeBlock.trimEnd()}\n`)
}

function timelineEventIds(cascadeBlock: string): string[] {
  return cascadeBlock
    .split('\n')
    .map((line) => line.match(/^\s{8}event:\s+(.+)$/)?.[1] ?? null)
    .filter((eventId): eventId is string => eventId !== null)
}

function conditionExpression(block: string): string | null {
  return block.match(/^ {6}condition: "([^"]+)"$/m)?.[1] ?? null
}

function conditionRef(atom: string): string | null {
  return atom.match(/\b([A-Za-z0-9_]+)\.(?:active|duration)\b/)?.[1] ?? null
}

function sanitizeConditionExpression(expression: string, retainedEventIds: Set<string>): string | null {
  const clauses = expression
    .split(/\s+OR\s+/)
    .map((clause) => clause.trim())
    .filter(Boolean)
    .flatMap((clause) => {
      const atoms = clause
        .split(/\s+AND\s+/)
        .map((atom) => atom.trim())
        .filter(Boolean)
      const hasMissingRef = atoms.some((atom) => {
        const ref = conditionRef(atom)
        return ref !== null && !retainedEventIds.has(ref)
      })
      return hasMissingRef ? [] : [atoms.join(' AND ')]
    })

  return clauses.length > 0 ? clauses.join(' OR ') : null
}

function resolveRetainedEvents(
  doc: string,
  seedEventIds: string[],
): { eventIds: string[]; sanitizedConditions: Map<string, string> } {
  const retainedEventIds = new Set(seedEventIds)
  const sanitizedConditions = new Map<string, string>()

  let changed = true
  while (changed) {
    changed = false
    for (const eventId of [...retainedEventIds]) {
      const match = doc.match(eventBlockPattern(eventId))
      if (!match) throw new Error(`Missing event block: ${eventId}`)
      const condition = conditionExpression(match[0])
      if (!condition) continue

      const sanitized = sanitizeConditionExpression(condition, retainedEventIds)
      if (sanitized === null) {
        retainedEventIds.delete(eventId)
        sanitizedConditions.delete(eventId)
        changed = true
        continue
      }

      if (sanitized !== condition) sanitizedConditions.set(eventId, sanitized)
    }
  }

  return {
    eventIds: seedEventIds.filter((eventId) => retainedEventIds.has(eventId)),
    sanitizedConditions,
  }
}

function sanitizeCauses(block: string, retainedEventIds: Set<string>): string {
  const match = block.match(/^ {4}causes: \[(.*)\]$/m)
  if (!match) return block

  const causes = match[1]
    .split(',')
    .map((value) => value.trim())
    .filter((value) => retainedEventIds.has(value))

  if (causes.length === 0) return block.replace(/^ {4}causes: \[.*\]\n/m, '')
  return block.replace(/^ {4}causes: \[.*\]$/m, `    causes: [${causes.join(', ')}]`)
}

function keepOnlyTimelineEvents(cascadeBlock: string, eventIds: string[]): string {
  const retainedEventIds = new Set(eventIds)
  let next = cascadeBlock
  for (const eventId of timelineEventIds(cascadeBlock)) {
    if (!retainedEventIds.has(eventId)) next = next.replace(timelineEntryPattern(eventId), '')
  }
  return next.replace(/\n{3,}/g, '\n\n')
}

function keepOnlyEvents(doc: string, eventIds: string[]): string {
  const retainedEventIds = new Set(eventIds)
  const blocks = eventIds.map((eventId) => {
    const match = doc.match(eventBlockPattern(eventId))
    if (!match) throw new Error(`Missing event block: ${eventId}`)
    return sanitizeCauses(match[0].trimEnd(), retainedEventIds)
  })
  return doc.replace(/^events:\n[\s\S]*?^cascades:\n/m, `events:\n${blocks.join('\n')}\n\ncascades:\n`)
}

function formatLoss(pct: number): string {
  return `-${Math.round(pct)}%`
}

function formatIncrease(pct: number): string {
  return `+${Math.round(pct)}%`
}

export function buildPdl(config: ScenarioConfig): string {
  let doc = replaceScenarioName(normalizedBaseTemplate, config.scenarioName)

  doc = updateEventBlock(doc, 'brazil_drought', (block) =>
    replaceDuration(replaceImpact(block, 'supply', formatLoss(config.soy.droughtLossPct)), config.soy.droughtDurationDays),
  )
  doc = updateEventBlock(doc, 'port_congestion', (block) =>
    replaceDuration(
      replaceImpact(block, 'supply', formatLoss(config.soy.portCongestionLossPct)),
      config.soy.portCongestionDurationDays,
    ),
  )
  doc = updateEventBlock(doc, 'gas_price_spike', (block) =>
    replaceDuration(
      replaceImpact(block, 'price', formatIncrease(config.energy.gasPriceIncreasePct)),
      config.energy.gasPriceDurationDays,
    ),
  )
  doc = updateEventBlock(doc, 'ammonia_halt', (block) =>
    replaceDuration(
      replaceImpact(block, 'supply', formatLoss(config.energy.ammoniaHaltLossPct)),
      config.energy.ammoniaHaltDurationDays,
    ),
  )
  doc = updateEventBlock(doc, 'oil_mill_slowdown', (block) =>
    replaceDuration(
      replaceImpact(block, 'supply', formatLoss(config.energy.oilMillSlowdownLossPct)),
      config.energy.oilMillSlowdownDurationDays,
    ),
  )

  doc = updateCascadeBlock(doc, 'soy_crisis_cascade', (block) => {
    const soyDays = Object.fromEntries(
      Object.entries(SOY_TIMELINE_OFFSETS).map(([eventId, offset]) => [eventId, config.soy.droughtDay + offset]),
    )
    soyDays.argentina_supply_increase = config.soy.droughtDay + config.soy.argentinaSupplyDay
    soyDays.port_congestion = config.soy.droughtDay + config.soy.portCongestionDay
    soyDays.port_route_shift = config.soy.droughtDay + config.soy.portCongestionDay
    soyDays.reserve_release = config.soy.droughtDay + config.soy.reserveReleaseDay
    soyDays.alternative_protein_activation = config.soy.droughtDay + config.soy.alternativeProteinDay
    soyDays.us_supply_activated = config.soy.droughtDay + config.soy.usEmergencyDay

    let next = setTimelineDays(block, soyDays)
    next = setTimelineEnabled(next, 'argentina_supply_increase', config.soy.argentinaSupplyEnabled, soyDays.argentina_supply_increase)
    next = setTimelineEnabled(next, 'port_congestion', config.soy.portCongestionEnabled, soyDays.port_congestion)
    next = setTimelineEnabled(next, 'port_route_shift', config.soy.portCongestionEnabled, soyDays.port_route_shift)
    next = setTimelineEnabled(next, 'reserve_release', config.soy.reserveReleaseEnabled, soyDays.reserve_release)
    next = setTimelineEnabled(
      next,
      'alternative_protein_activation',
      config.soy.alternativeProteinEnabled,
      soyDays.alternative_protein_activation,
    )
    next = setTimelineEnabled(next, 'us_supply_activated', config.soy.usEmergencyEnabled, soyDays.us_supply_activated)
    return next.replace(/\n{3,}/g, '\n\n')
  })

  doc = updateCascadeBlock(doc, 'energy_food_cascade', (block) => {
    const energyDays = Object.fromEntries(
      Object.entries(ENERGY_TIMELINE_OFFSETS).map(([eventId, offset]) => [eventId, config.energy.gasPriceDay + offset]),
    )
    energyDays.ammonia_halt = config.energy.gasPriceDay + config.energy.ammoniaHaltDay
    energyDays.oil_mill_slowdown = config.energy.gasPriceDay + config.energy.oilMillSlowdownDay
    energyDays.reserve_release = config.energy.gasPriceDay + config.energy.reserveReleaseDay
    energyDays.alternative_protein_activation = config.energy.gasPriceDay + config.energy.alternativeProteinDay

    let next = setTimelineDays(block, energyDays)
    next = setTimelineEnabled(next, 'ammonia_halt', config.energy.ammoniaHaltEnabled, energyDays.ammonia_halt)
    next = setTimelineEnabled(
      next,
      'oil_mill_slowdown',
      config.energy.oilMillSlowdownEnabled,
      energyDays.oil_mill_slowdown,
    )
    next = setTimelineEnabled(next, 'reserve_release', config.energy.reserveReleaseEnabled, energyDays.reserve_release)
    next = setTimelineEnabled(
      next,
      'alternative_protein_activation',
      config.energy.alternativeProteinEnabled,
      energyDays.alternative_protein_activation,
    )
    return next.replace(/\n{3,}/g, '\n\n')
  })

  const selectedCascade = doc.match(cascadeBlockPattern(config.cascadeId))?.[0]
  if (!selectedCascade) throw new Error(`Missing cascade block: ${config.cascadeId}`)

  const { eventIds, sanitizedConditions } = resolveRetainedEvents(doc, timelineEventIds(selectedCascade))
  for (const [eventId, condition] of sanitizedConditions) {
    doc = updateEventBlock(doc, eventId, (block) => replaceCondition(block, condition))
  }

  doc = keepOnlyEvents(doc, eventIds)
  doc = keepOnlyCascade(doc, keepOnlyTimelineEvents(selectedCascade, eventIds))
  return `${GENERATED_HEADER}${doc.trimEnd()}\n`
}

export function buildRosterSidecar(config: ScenarioConfig): string {
  const scenarioFileName = suggestedFileName(config)
  const roster = normalizedRosterTemplate.replace(
    /^# Sidecar for .*?:/m,
    `# Sidecar for ${scenarioFileName}:`,
  )
  return `${GENERATED_ROSTER_HEADER}${roster.trimEnd()}\n`
}

export function cascadeSummary(config: ScenarioConfig): string[] {
  if (config.cascadeId === 'soy_crisis_cascade') {
    return [
      `Drought ${config.soy.droughtLossPct}% for ${config.soy.droughtDurationDays}d`,
      `Port congestion ${config.soy.portCongestionEnabled ? 'on' : 'off'}`,
      `Argentina fallback ${config.soy.argentinaSupplyEnabled ? 'on' : 'off'}`,
      `US emergency supply ${config.soy.usEmergencyEnabled ? 'on' : 'off'}`,
    ]
  }

  return [
    `Gas price +${config.energy.gasPriceIncreasePct}% for ${config.energy.gasPriceDurationDays}d`,
    `Ammonia halt ${config.energy.ammoniaHaltEnabled ? 'on' : 'off'}`,
    `Oil mill slowdown ${config.energy.oilMillSlowdownEnabled ? 'on' : 'off'}`,
    `Strategic reserves ${config.energy.reserveReleaseEnabled ? 'on' : 'off'}`,
  ]
}

export function cascadeLabel(cascadeId: CascadeId): string {
  return CASCADE_LABEL[cascadeId]
}

export function suggestedFileName(config: ScenarioConfig): string {
  const base = (config.scenarioName.trim() || cascadeLabel(config.cascadeId)).toLowerCase()
  const slug = base
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48)
  return `${slug || config.cascadeId}.pdl.yaml`
}

export function suggestedRosterFileName(config: ScenarioConfig): string {
  return suggestedFileName(config).replace(/\.pdl\.yaml$/, '.roster.yaml')
}
