import baseTemplate from './templates/s1-soja.template.pdl.yaml?raw'

export type CascadeId = 'soy_crisis_cascade' | 'energy_food_cascade'

interface SoyConfig {
  droughtLossPct: number
  droughtDurationDays: number
  droughtDay: number
  portCongestionEnabled: boolean
  portCongestionLossPct: number
  portCongestionDurationDays: number
  portCongestionDay: number
  argentinaSupplyEnabled: boolean
  argentinaSupplyDay: number
  usEmergencyEnabled: boolean
  usEmergencyDay: number
  reserveReleaseEnabled: boolean
  reserveReleaseDay: number
  alternativeProteinEnabled: boolean
  alternativeProteinDay: number
}

interface EnergyConfig {
  gasPriceIncreasePct: number
  gasPriceDurationDays: number
  gasPriceDay: number
  ammoniaHaltEnabled: boolean
  ammoniaHaltLossPct: number
  ammoniaHaltDurationDays: number
  ammoniaHaltDay: number
  oilMillSlowdownEnabled: boolean
  oilMillSlowdownLossPct: number
  oilMillSlowdownDurationDays: number
  oilMillSlowdownDay: number
  reserveReleaseEnabled: boolean
  reserveReleaseDay: number
  alternativeProteinEnabled: boolean
  alternativeProteinDay: number
}

export interface ScenarioConfig {
  scenarioName: string
  cascadeId: CascadeId
  soy: SoyConfig
  energy: EnergyConfig
}

export const defaultScenarioConfig: ScenarioConfig = {
  scenarioName: 'Interactive supply chain scenario',
  cascadeId: 'soy_crisis_cascade',
  soy: {
    droughtLossPct: 40,
    droughtDurationDays: 90,
    droughtDay: 0,
    portCongestionEnabled: true,
    portCongestionLossPct: 20,
    portCongestionDurationDays: 30,
    portCongestionDay: 21,
    argentinaSupplyEnabled: true,
    argentinaSupplyDay: 14,
    usEmergencyEnabled: true,
    usEmergencyDay: 45,
    reserveReleaseEnabled: true,
    reserveReleaseDay: 28,
    alternativeProteinEnabled: true,
    alternativeProteinDay: 35,
  },
  energy: {
    gasPriceIncreasePct: 200,
    gasPriceDurationDays: 180,
    gasPriceDay: 0,
    ammoniaHaltEnabled: true,
    ammoniaHaltLossPct: 70,
    ammoniaHaltDurationDays: 90,
    ammoniaHaltDay: 7,
    oilMillSlowdownEnabled: true,
    oilMillSlowdownLossPct: 30,
    oilMillSlowdownDurationDays: 60,
    oilMillSlowdownDay: 14,
    reserveReleaseEnabled: true,
    reserveReleaseDay: 21,
    alternativeProteinEnabled: true,
    alternativeProteinDay: 28,
  },
}

const GENERATED_HEADER = [
  '# Generated by the integrated simenv scenario configurator.',
  '# Save this document as *.pdl.yaml and pass it to provider_simenv.main with --pdl.',
  '',
].join('\n')

const CASCADE_LABEL: Record<CascadeId, string> = {
  soy_crisis_cascade: 'Soy crisis cascade',
  energy_food_cascade: 'Energy-food cascade',
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function replaceScenarioName(doc: string, name: string): string {
  const scenarioName = name.trim() || defaultScenarioConfig.scenarioName
  return doc.replace(/(^scenario:\n(?: {2}.*\n)+? {2}name: ).*$/m, `$1${JSON.stringify(scenarioName)}`)
}

function eventBlockPattern(eventId: string): RegExp {
  return new RegExp(`(^  - id: ${escapeRegex(eventId)}\\n[\\s\\S]*?)(?=^  - id: |^cascades:|\\Z)`, 'm')
}

function cascadeBlockPattern(cascadeId: CascadeId): RegExp {
  return new RegExp(`(^  - id: ${escapeRegex(cascadeId)}\\n[\\s\\S]*?)(?=^  - id: |\\Z)`, 'm')
}

function timelineEntryPattern(eventId: string): RegExp {
  return new RegExp(
    `(^      - at: .*\\n        event: ${escapeRegex(eventId)}\\n[\\s\\S]*?)(?=^      - at: |^    probability:|\\Z)`,
    'm',
  )
}

function updateEventBlock(
  doc: string,
  eventId: string,
  updater: (block: string) => string,
): string {
  const pattern = eventBlockPattern(eventId)
  const match = doc.match(pattern)
  if (!match) throw new Error(`Missing event block: ${eventId}`)
  return doc.replace(pattern, updater(match[0]))
}

function updateCascadeBlock(
  doc: string,
  cascadeId: CascadeId,
  updater: (block: string) => string,
): string {
  const pattern = cascadeBlockPattern(cascadeId)
  const match = doc.match(pattern)
  if (!match) throw new Error(`Missing cascade block: ${cascadeId}`)
  return doc.replace(pattern, updater(match[0]))
}

function replaceImpact(block: string, field: 'supply' | 'price', value: string): string {
  return block.replace(new RegExp(`(^      ${field}: ).*$`, 'm'), `$1${JSON.stringify(value)}`)
}

function replaceDuration(block: string, durationDays: number): string {
  return block.replace(/^ {6}duration: .*$/m, `      duration: ${Math.round(durationDays)}d`)
}

function setTimelineDay(block: string, eventId: string, day: number): string {
  const pattern = timelineEntryPattern(eventId)
  const match = block.match(pattern)
  if (!match) throw new Error(`Missing timeline entry: ${eventId}`)
  return block.replace(pattern, match[0].replace(/^ {6}- at: .*$/m, `      - at: ${Math.round(day)}d`))
}

function setTimelineEnabled(block: string, eventId: string, enabled: boolean, day: number): string {
  const pattern = timelineEntryPattern(eventId)
  const match = block.match(pattern)
  if (!match) throw new Error(`Missing timeline entry: ${eventId}`)
  if (!enabled) return block.replace(pattern, '')
  return block.replace(pattern, match[0].replace(/^ {6}- at: .*$/m, `      - at: ${Math.round(day)}d`))
}

function shiftTimelineDays(block: string, delta: number): string {
  if (delta === 0) return block
  return block.replace(/^ {6}- at: (\d+)d$/gm, (_, day) => `      - at: ${Math.max(0, Number(day) + delta)}d`)
}

function keepOnlyCascade(doc: string, cascadeId: CascadeId): string {
  const match = doc.match(cascadeBlockPattern(cascadeId))
  if (!match) throw new Error(`Missing cascade block: ${cascadeId}`)
  return doc.replace(/^cascades:\n[\s\S]*$/m, `cascades:\n${match[0].trimEnd()}\n`)
}

function timelineEventIds(cascadeBlock: string): string[] {
  return [...cascadeBlock.matchAll(/^ {8}event: (.+)$/gm)].map((match) => match[1])
}

function sanitizeCauses(block: string, retainedEventIds: Set<string>): string {
  const match = block.match(/^ {4}causes: \[(.*)\]$/m)
  if (!match) return block

  const causes = match[1]
    .split(',')
    .map((value) => value.trim())
    .filter((value) => retainedEventIds.has(value))

  if (causes.length === 0) return block.replace(/^ {4}causes: \[.*\]\n/m, '')
  return block.replace(/^ {4}causes: \[.*\]$/m, `    causes: [${causes.join(', ')}]`)
}

function keepOnlyEvents(doc: string, eventIds: string[]): string {
  const retainedEventIds = new Set(eventIds)
  const blocks = eventIds.map((eventId) => {
    const match = doc.match(eventBlockPattern(eventId))
    if (!match) throw new Error(`Missing event block: ${eventId}`)
    return sanitizeCauses(match[0].trimEnd(), retainedEventIds)
  })
  return doc.replace(/^events:\n[\s\S]*?^cascades:\n/m, `events:\n${blocks.join('\n')}\n\ncascades:\n`)
}

function formatLoss(pct: number): string {
  return `-${Math.round(pct)}%`
}

function formatIncrease(pct: number): string {
  return `+${Math.round(pct)}%`
}

export function buildPdl(config: ScenarioConfig): string {
  let doc = replaceScenarioName(baseTemplate.trimEnd() + '\n', config.scenarioName)

  doc = updateEventBlock(doc, 'brazil_drought', (block) =>
    replaceDuration(replaceImpact(block, 'supply', formatLoss(config.soy.droughtLossPct)), config.soy.droughtDurationDays),
  )
  doc = updateEventBlock(doc, 'port_congestion', (block) =>
    replaceDuration(
      replaceImpact(block, 'supply', formatLoss(config.soy.portCongestionLossPct)),
      config.soy.portCongestionDurationDays,
    ),
  )
  doc = updateEventBlock(doc, 'gas_price_spike', (block) =>
    replaceDuration(
      replaceImpact(block, 'price', formatIncrease(config.energy.gasPriceIncreasePct)),
      config.energy.gasPriceDurationDays,
    ),
  )
  doc = updateEventBlock(doc, 'ammonia_halt', (block) =>
    replaceDuration(
      replaceImpact(block, 'supply', formatLoss(config.energy.ammoniaHaltLossPct)),
      config.energy.ammoniaHaltDurationDays,
    ),
  )
  doc = updateEventBlock(doc, 'oil_mill_slowdown', (block) =>
    replaceDuration(
      replaceImpact(block, 'supply', formatLoss(config.energy.oilMillSlowdownLossPct)),
      config.energy.oilMillSlowdownDurationDays,
    ),
  )

  doc = updateCascadeBlock(doc, 'soy_crisis_cascade', (block) => {
    let next = shiftTimelineDays(block, config.soy.droughtDay)
    next = setTimelineDay(next, 'brazil_drought', config.soy.droughtDay)
    next = setTimelineEnabled(
      next,
      'argentina_supply_increase',
      config.soy.argentinaSupplyEnabled,
      config.soy.droughtDay + config.soy.argentinaSupplyDay,
    )
    next = setTimelineEnabled(
      next,
      'port_congestion',
      config.soy.portCongestionEnabled,
      config.soy.droughtDay + config.soy.portCongestionDay,
    )
    next = setTimelineEnabled(
      next,
      'port_route_shift',
      config.soy.portCongestionEnabled,
      config.soy.droughtDay + config.soy.portCongestionDay,
    )
    next = setTimelineEnabled(
      next,
      'reserve_release',
      config.soy.reserveReleaseEnabled,
      config.soy.droughtDay + config.soy.reserveReleaseDay,
    )
    next = setTimelineEnabled(
      next,
      'alternative_protein_activation',
      config.soy.alternativeProteinEnabled,
      config.soy.droughtDay + config.soy.alternativeProteinDay,
    )
    next = setTimelineEnabled(
      next,
      'us_supply_activated',
      config.soy.usEmergencyEnabled,
      config.soy.droughtDay + config.soy.usEmergencyDay,
    )
    return next.replace(/\n{3,}/g, '\n\n')
  })

  doc = updateCascadeBlock(doc, 'energy_food_cascade', (block) => {
    let next = shiftTimelineDays(block, config.energy.gasPriceDay)
    next = setTimelineDay(next, 'gas_price_spike', config.energy.gasPriceDay)
    next = setTimelineEnabled(
      next,
      'ammonia_halt',
      config.energy.ammoniaHaltEnabled,
      config.energy.gasPriceDay + config.energy.ammoniaHaltDay,
    )
    next = setTimelineEnabled(
      next,
      'oil_mill_slowdown',
      config.energy.oilMillSlowdownEnabled,
      config.energy.gasPriceDay + config.energy.oilMillSlowdownDay,
    )
    next = setTimelineEnabled(
      next,
      'reserve_release',
      config.energy.reserveReleaseEnabled,
      config.energy.gasPriceDay + config.energy.reserveReleaseDay,
    )
    next = setTimelineEnabled(
      next,
      'alternative_protein_activation',
      config.energy.alternativeProteinEnabled,
      config.energy.gasPriceDay + config.energy.alternativeProteinDay,
    )
    return next.replace(/\n{3,}/g, '\n\n')
  })

  const selectedCascade = doc.match(cascadeBlockPattern(config.cascadeId))?.[0]
  if (!selectedCascade) throw new Error(`Missing cascade block: ${config.cascadeId}`)

  doc = keepOnlyEvents(doc, timelineEventIds(selectedCascade))
  doc = keepOnlyCascade(doc, config.cascadeId)
  return `${GENERATED_HEADER}${doc.trimEnd()}\n`
}

export function cascadeSummary(config: ScenarioConfig): string[] {
  if (config.cascadeId === 'soy_crisis_cascade') {
    return [
      `Drought ${config.soy.droughtLossPct}% for ${config.soy.droughtDurationDays}d`,
      `Port congestion ${config.soy.portCongestionEnabled ? 'on' : 'off'}`,
      `Argentina fallback ${config.soy.argentinaSupplyEnabled ? 'on' : 'off'}`,
      `US emergency supply ${config.soy.usEmergencyEnabled ? 'on' : 'off'}`,
    ]
  }

  return [
    `Gas price +${config.energy.gasPriceIncreasePct}% for ${config.energy.gasPriceDurationDays}d`,
    `Ammonia halt ${config.energy.ammoniaHaltEnabled ? 'on' : 'off'}`,
    `Oil mill slowdown ${config.energy.oilMillSlowdownEnabled ? 'on' : 'off'}`,
    `Strategic reserves ${config.energy.reserveReleaseEnabled ? 'on' : 'off'}`,
  ]
}

export function cascadeLabel(cascadeId: CascadeId): string {
  return CASCADE_LABEL[cascadeId]
}

export function suggestedFileName(config: ScenarioConfig): string {
  const base = (config.scenarioName.trim() || cascadeLabel(config.cascadeId)).toLowerCase()
  const slug = base
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48)
  return `${slug || config.cascadeId}.pdl.yaml`
}
